filter:
  excluded_paths:
    - 'sdk/php/tests/*'

checks:
  php:
    code_rating: true
    duplication: false

build:
  environment:
    mysql: false
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    rabbitmq: false
  nodes:
    php56:
      environment:
        php: 5.6
      tests:
        override:
          -
            command: './vendor/bin/phpunit --configuration ./sdk/php/phpunit.xml'
    php70:
      environment:
        php: 7.0
      tests:
        override:
          -
            command: './vendor/bin/phpunit --configuration ./sdk/php/phpunit.xml'
    php71:
      environment:
        php: 7.1
      tests:
        override:
          -
            command: './vendor/bin/phpunit --configuration ./sdk/php/phpunit.xml'
